[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding_dapp = "EYH93EyjromEmPgJfp6918j7uMBMc1YKb41qVMbS5zst"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\sachi\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
